version: '3'
services:
  solr:
    image: solr:8
    container_name: solr
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - gettingstarted
    networks:
      mired1:
        ipv4_address: 172.18.1.4
networks:
  mired1:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.1.0/24
